# Site settings
title: Zaalvoetbal Toogkletsers Elewijt
email: kevin.van.ransbeeck@gmail.com
description: >
  Website van de zaalvoetbalploeg "De Toogkletsers" Elewijt.
#baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
